name: 'Detected Changes'
description: 'A Github action that returns a list of directories that have been modified.'
inputs:
  repo-token:
    description: 'The github token used to authenticate'
    required: true
outputs:
  files_changed:
    description: 'The files changed between the default branch and the sha being built'
runs:
  using: 'node12'
  main: 'index.js'
