on: [push]

jobs:
  detect_changes_job:
    runs-on: ubuntu-latest
    name: A job that prints diffs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./
        id: hit_the_diff
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The output was ${{ steps.hit_the_diff.outputs.files_changed }}"
